Repository compilerCompiler/compilerCompiler, pull requests merged in 2021-12, with the labels that each got.

#100 Unit Tests
  app/build.gradle
  app/src/main/java/com/upb/vlibrary/ui/register/RegisterFragment.kt
  app/src/main/java/com/upb/vlibrary/ui/search/ArticleSearchFragment.kt
  app/src/main/java/com/upb/vlibrary/ui/search/ArticleSearchInfoFragment.kt
  app/src/main/java/com/upb/vlibrary/ui/unitTests/BookAuthor.kt
  app/src/main/java/com/upb/vlibrary/ui/unitTests/BookTest.kt
  app/src/main/java/com/upb/vlibrary/ui/unitTests/Password.kt
  app/src/main/java/com/upb/vlibrary/ui/unitTests/RegistrationUtil.kt
  app/src/main/java/com/upb/vlibrary/ui/unitTests/UsernameUtil.kt
  app/src/test/java/com/upb/vlibrary/ui/unitTests/BookAuthorTest.kt
  app/src/test/java/com/upb/vlibrary/ui/unitTests/BookTestTest.kt
  app/src/test/java/com/upb/vlibrary/ui/unitTests/PasswordTest.kt
  app/src/test/java/com/upb/vlibrary/ui/unitTests/RegistrationUtilTest.kt
  app/src/test/java/com/upb/vlibrary/ui/unitTests/UsernameUtilTest.kt
Labels: L, sprint-5

#101 Feature/multimedia and support
  app/build.gradle
  app/src/main/java/com/upb/vlibrary/ListOfVideosAdapter.kt
  app/src/main/java/com/upb/vlibrary/ListOfVideosViewModel.kt
  app/src/main/java/com/upb/vlibrary/Video.kt
  app/src/main/java/com/upb/vlibrary/data/multimedia/MultimediaRepository.kt
  app/src/main/java/com/upb/vlibrary/data/multimedia/network/MultimediaAPI.kt
  app/src/main/java/com/upb/vlibrary/data/multimedia/network/MultimediaNetworkController.kt
  app/src/main/java/com/upb/vlibrary/data/multimedia/network/MultimediaNetworkControllerImp.kt
  app/src/main/java/com/upb/vlibrary/ui/helpContact/Contact.kt
  app/src/main/java/com/upb/vlibrary/ui/helpContact/ContactFragment.kt
  app/src/main/java/com/upb/vlibrary/ui/helpContact/ContactListAdapter.kt
  app/src/main/java/com/upb/vlibrary/ui/helpContact/ContactsDataSource.kt
  app/src/main/java/com/upb/vlibrary/ui/helpContact/HelpFragment.kt
  app/src/main/java/com/upb/vlibrary/ui/menuUser/MenuUserFragment.kt
  app/src/main/java/com/upb/vlibrary/ui/multimedia/MultimediaMainFragment.kt
  app/src/main/java/com/upb/vlibrary/ui/multimedia/MultimediaPageFragment.kt
  app/src/main/res/layout/contact_info.xml
  app/src/main/res/layout/fragment_multimedia_main.xml
  app/src/main/res/layout/fragment_multimedia_page.xml
  app/src/main/res/layout/multimedia_item.xml
  app/src/main/res/navigation/main_app_nav_graph.xml
Labels: S, sprint-5

#110 Feature/button graph
  app/build.gradle
  app/src/main/java/com/upb/vlibrary/CompleteListOfUsersViewModel.kt
  app/src/main/java/com/upb/vlibrary/GraficaFragment.kt
  app/src/main/java/com/upb/vlibrary/ListOfUsersViewModel.kt
  app/src/main/java/com/upb/vlibrary/NormalUsersTotalViewModel.kt
  app/src/main/java/com/upb/vlibrary/UsuarioPersona.kt
  app/src/main/java/com/upb/vlibrary/data/user/UserRepository.kt
  app/src/main/java/com/upb/vlibrary/data/user/network/UserAPI.kt
  app/src/main/java/com/upb/vlibrary/data/user/network/UserNetworkController.kt
  app/src/main/java/com/upb/vlibrary/data/user/network/UserNetworkControllerImp.kt
  app/src/main/java/com/upb/vlibrary/ui/menuAdmi/MenuAdminFragment.kt
  app/src/main/res/drawable/blue_square.png
  app/src/main/res/drawable/button_background.xml
  app/src/main/res/drawable/green_square.png
  app/src/main/res/layout/admin_info.xml
  app/src/main/res/layout/fragment_grafica.xml
  app/src/main/res/layout/fragment_menu_admin.xml
  app/src/main/res/layout/fragment_user_details.xml
  app/src/main/res/navigation/main_app_nav_graph.xml
  build.gradle
Labels: S, Sprint-6
